### ISSUE TITLE
`through2@4.0.2` chromium binary is not available for arm64

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/citgm#1040]
We've experienced some issues on v21.x when running the suite on `osx11` 

Ref: 

* https://ci.nodejs.org/job/citgm-smoker/3351/nodes=osx11/testReport/junit/(root)/citgm/through2_v4_0_2/
* https://ci.nodejs.org/job/citgm-smoker/3364/nodes=osx11/testReport/junit/(root)/citgm/through2_v4_0_2/

Can we skip an environment in a specific version? v21.x >=

**Comment by targos** [comment]
Can this be fixed in `through2`? I doubt it actually needs puppeteer for its test.

To answer your question, I don't know if that's the intended way, but it seems you can combine conditions by using an object:
```
"skip": {
  "osx11": ">=21"
}
```

https://github.com/nodejs/citgm/blob/e2a0731ea6bf191cbdfdbbe9f820a2483ca19cfc/lib/match-conditions.js#L81-L89

**Comment by targos** [comment]
Fixed in https://github.com/nodejs/citgm/pull/1085
