### ISSUE TITLE
Add ability to run test multiple times

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#122]
If we have a single suite that is flaky it would be nice to be able to stress test a specific modules test suite. 

Potential Api's

```
citgm --repeat || -r 100 some-module
```

or

```
citgm-stress module-name
```

I prefer the first, although it might be a bit of a hack to add to citgm. Likely the logic will live in the bin, not the runner... and if it makes the code in the citgm bin nasty I'll likely want to make a custom bin

**Comment by jasnell** [comment]
+1 ... but I think the custom bin is likely the better option

**Comment by TheAlphaNerd** [comment]
custom bin it is!

**Comment by MylesBorins** [comment]
@gdams were you going to tackle this again or is it open for others to dive in?

**Comment by gdams** [comment]
@MylesBorins so my PR is nearly there, It currently runs citgm `x` number of times but this involves fetching the tarballs and then running the test suite each time (essentially I have a for loop on the async waterfall). So the only thing that I really wanted to improve was adding the feature so that it only gets the tarball once and then runs the tests multiple times
