### ISSUE TITLE
public website for CITGM

### ISSUE THREAD

**Issue by bcoe** [nodejs/citgm#137]
Is there a public website where I can view the most recent test runs of CITGM?

If not, this would rock \o/ 

If there is already a website, could you link to it in the documentation?

**Comment by Fishrock123** [comment]
That would be https://ci.nodejs.org/view/Node.js-citgm/job/thealphanerd-smoker/ -- I'm not sure it's worth the time investment to proxy that to something prettier, getting the info out of Kenkins would not be trivial.

I'll make a PR for it.

**Comment by TheAlphaNerd** [comment]
I think he was referring to a marketing page, or something that is more
informative

**Comment by jasnell** [comment]
A separate microsite along the same basic lines at benchmarking.nodejs.org would be interesting to explore if only to explain the project and help get the word out. I've been stewing over whether it would be possible to get a badge system in place so that module developers can advertise on their readme pages that their stuff passes citgm testing. That would be a bit more longer term tho

**Comment by Fishrock123** [comment]
> Is there a public website where I can view the most recent test runs of CITGM?

Sounds like jenkins to me.

**Comment by Fishrock123** [comment]
Also I haven't made a PR yet because GitHub is still having issues and won't see my branch...
