### ISSUE TITLE
Gotta test em' all

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/citgm#146]
master: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/319/
v6: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/324/
v5: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/325/
v4: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/323/
v0.12: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/326/
v0.10: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/327/

**Comment by rvagg** [comment]
from what I can tell, the failures I poked at on v0.10 and v0.12 are all `notarget No compatible version found` problems, where npm can't find the version that's needed by some dependency. Most notably raw-body@2.1.7 was not found even though it's in npm with a timestamp of `2016-06-19T19:14:25.247Z`. I've seen these kinds of weird problems before but only when using `--cache-min`, I suppose it's because that prevents newer metadata from being fetched, which is a problem when dependencies shift their required versions up to a recent version, like raw-body in this case.

I think perhaps we should shorten `--cache-min` to a few days, a week max.

**Comment by TheAlphaNerd** [comment]
I think it may make sense to just revert cache-min all together. We were
not seeing that much of an improvement

**Comment by TheAlphaNerd** [comment]
Closing this as there are too many failures related to cache-min. I'm going to revert that change and then re-run these tests
