### ISSUE TITLE
Running CITGM on Windows

### ISSUE THREAD

**Issue by gibfahn** [nodejs/citgm#157]
It seems like a good idea to have an issue in here to document the problems people are seeing running CitGM on windows.

I know @joaocgreis and @TheAlphaNerd have been trying to do this, and we run it on our Jenkins instance as well. We end up seeing quite a few failures that are windows specific.

cc. @currykitten who is working on this as well.

FYI @mhdawson

**Comment by CurryKitten** [comment]
Am going through our list of failures.  I've just looked at glob which is failing on windows because of a case mismatch on the drive letter. @isaacs has already put a fix in for this, which I've tested and works well, but this hasn't gone into a release as yet.

**Comment by TheAlphaNerd** [comment]
@CurryKitten would you be able to share the list of failures for us?

**Comment by CurryKitten** [comment]
@TheAlphaNerd Sure - I haven't been able to go through each one just to double-check there's nothing odd in one of our environments that could account for the errors, but currently on Win7/2012 on x86/64 we're seeing -

### Failure: 
### 1. glob@latest
### 2. rimraf@latest
### 3. vinyl@latest
### 4. binary-split@latest
### 5. spdy-transport@latest
### 6. jsonstream@latest
### 7. csv-parser@latest
### 8. node-uuid@latest
### 9. winston@latest

rimraf (as you might guess, I'm just heading down the list one by one) seems to have weirdness on Windows, where a lot of the file operations fail unless you run as administrator (obviously not ideal) and some other failures because of mismatching forward/backward slashes.  I'll open up an issue there once I've finished looking

**Comment by TheAlphaNerd** [comment]
thanks @CurryKitten 

I should be getting a windows box soon and will be able to start hunting down and hopefully fixing some of these failures!

**Comment by GeorgeAdams95** [comment]
I believe that some of these tests have been fixed on windows now. I will try and populate a list of current failing modules

**Comment by phestermcs** [comment]
What is the current state of getting citgm running on Windows? I'd like to help. It seems the may mean helping other projects, no problem.

**Comment by gibfahn** [comment]
@phestermcs There's https://github.com/nodejs/citgm/pull/230, which should help add support for windows. 

We (IBM) have already been running CitGM in the Git Bash shell on Windows for about six months now, without seeing too many problems. The issue with running on CMD is mostly due to modules whose `npm test` uses bash-specific code.

**Comment by phestermcs** [comment]
Thank you @gibfahn. It would appear there's a fair amount of work to get citgm running in windows, and I wouldn't be surprised if it always plays second fiddle with respect to package authors keeping their scripts working for windows. Thanks for your efforts.

I did run citgm within win10 bash shell, and it kinda worked, although one of the tests caused a segfault, and it did seem to run a bit slower. back to linux vms :)

**Comment by targos** [comment]
I think this can be closed for now because CITGM mostly works on Windows, including with native modules.
We can open separate issues for problems with specific modules.
