### ISSUE TITLE
Looks like a bug in canary

### ISSUE THREAD

**Issue by acierto** [nodejs/citgm#197]
Bogdans-MBP-2:~ bogdannechyporenko$ citgm git+http@github.com:ramda/ramda.git
info:    starting            | git+http@github.com:ramda/ramda.git
info:    npm:                | Downloading project: git+http@github.com:ramda/ramda.git
info:    npm:                | Project downloaded ramda-0.22.1.tgz
info:    npm:                | install started
info:    npm:                | install successfully completed
info:    npm:                | test suite started
error:   failure             | The canary is dead:
error:   failing module(s)   |
error:   module name:        | 3b5b8d64161ac4e4be054aac549f32c7f4693fe6
error:   version:            |
error:   error:              | The canary is dead:
error:   error:              | undefined

**Comment by TheAlphaNerd** [comment]
@acierto that looks like a test suite is failing, rather than a bug in citgm.

You may want to try running it with more verbosity `citgm -v verbose git+http@github.com:ramda/ramda.git` if you would like some more information about what is happening in the failure.

I'm going to close this issue but please feel free to keep the conversation going
