### ISSUE TITLE
Evaluate Node Checker

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/citgm#21]
http://nodechecker.com/

**Comment by TheAlphaNerd** [comment]
It looks like this code base may solve many of the problem CITGM is planning to. I will reach out to the author and talk about what we are trying to do

**Comment by rvagg** [comment]
I'm pretty sure this is a docker solution, which citgm was meant to move us beyond. Prior to citgm I was using https://github.com/rvagg/iojs-smoke-tests which is Docker-based and has all of the drawbacks thereof.

**Comment by jasnell** [comment]
@rvagg at this point I've asked @TheAlphaNerd to go through and investigate a broad range of options on how we can move citgm forward and improve on it's overall function. He's largely in fact finding mode at this point, investigating other approaches.

**Comment by rvagg** [comment]
OK, don't mind me then!

**Comment by TheAlphaNerd** [comment]
I appreciate the insight. @jasnell was mentioning that not being tied to docker makes the code base much more portable between os's, which I had not considered. That will likely make the engine for the node checker project a no go, but some of the other modules might be useful. At the very least I'd love to hear the thoughts of the author

**Comment by rvagg** [comment]
Well, one approach to consider here is a two-level check if it's easier (Docker does make it easier to do tests with complex environment requirements). We could have one set of tests running automatically (daily?) against the current codebase and then a more thorough suite run by releasers prior to cutting a release and that could be more involved or take more time / resources. One of the other things that Docker buys us is security, even though we're choosing common ecosystem modules, the idea of running whatever code they release in our test infrastructure worries me a little bit because of the potential for pollution and subversion by malicious code. (`if (runningInNodeCoreSmokeTests) { doSomethingNastyToTheInfra() })`).

**Comment by TheAlphaNerd** [comment]
No longer relevant for now
