### ISSUE TITLE
Should we still report skipped modules?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#443]
Currently we don't... if a module is skipped in our lookup it is a no-op. This can be confusing and doesn't make the results in CI exactly "accurate"

**Comment by aruneshchandra** [comment]
Yes please! Having an account for all the modules in the report at the end will be very helpful. Thanx

**Comment by MylesBorins** [comment]
I've marked this as a good first contribution

[Here](https://github.com/nodejs/citgm/blob/master/bin/citgm-all.js#L112-L114) is where you would need to do the changes. Currently the logic simply skips running the module... we would need to alternatively append the module as skipped

**Comment by aruneshchandra** [comment]
//cc: @boingoing who looked into this reporting for Node-ChakraCore

**Comment by targos** [comment]
Thanks to https://github.com/nodejs/citgm/pull/504, skipped modules are now marked as such and reported by the "logger" reporter.
The other reporters should also be updated. See https://github.com/nodejs/citgm/pull/504#issuecomment-345624911.

**Comment by BeniCheni** [comment]
Hello, @targos et al,

Reviewed this open “good first issue” issue. Seems from [#504 (comment)](
https://github.com/nodejs/citgm/pull/504#issuecomment-345624911) that the markdown / tap / xunit reporters.

Is this issue still “current” since it’s from 2017? markdown reporter should be straightforward as comment suggested. I’m happy to try out the markdown reporter w. skipped modules.
