### ISSUE TITLE
Allow module flakyness changes without code review

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/citgm#51]
Modules may become flaky / unflaky at a very fast rate. Would people be open to changes to module flakyness to be merged without code review? (As long as it is documented)

**Comment by rvagg** [comment]
In your experience with this, how hard is it to distinguish between flaky and failure because the canary is dead? My concern is that we'd be writing off too many failures as nothing to do with core when perhaps it is.

**Comment by mhdawson** [comment]
The question is also what else should we do in addition to marking them flaky. For example we may want to open an issue on the module before we disable tests and track those issues so we know when to re-enable.  Otherwise we'll end up disabling and probably forgetting about them which could just erode coverage over time.

**Comment by jasnell** [comment]
Catching these kinds of issues is exactly what citgm is for, isn't it? I have no issue with automatically marking modules as being flaky but as @mhdawson mentioned we need to make sure there's a process for following up. Essentially: if a test fails in citgm, there needs to be a determination of if the failure is caused by a change in core or a change in the module. If it's due to a change in the module, then automatically marking as flaky and opening an issue in the module repo would be appropriate.

**Comment by TheAlphaNerd** [comment]
Currently CITGM runs at loglevel verbose by default, this output the entire test output for every tested module making it easy to track what's going on. You can also specify test command, allowing you to run citgm CI against only a single module.

Some modules are flaky during install / setup. Last night for example a change to ```torrent-stream``` caused ```npm install``` to stop resolving the module tree properly. This failure is happening on all OS's on all version of node using npm 3.3.12

I have been documenting flaky modules in the issue tracker here, as well as following up with the module authors to get things fixed upstream.

Now I wasn't imagining that we would automate the marking as flaky, more that if a flaky module is found we can mark it without going through the review process, assuming guidelines are followed

**Comment by Trott** [comment]
Is it sensible to have CITGM always install a specific version rather than latest? Then that will slow down the flakiness toggling. Downside is you have to manually update the versions periodically and deal with the flakiness then, but at least it's under your control as to when to deal with newly flaky modules. 

Alternatively: Always install specific known-good versions and fail hard (red) if one of them fails. Always install the latest version and log a warning (yellow) if it fails. Deal with the yellows aggressively.

**Comment by TheAlphaNerd** [comment]
This could potentially be done. That being said in the case of torrent-stream it was a patch that caused things to break, and the breakages are in NPM.

Personally I'm still +1 on keeping it to testing latest

**Comment by TheAlphaNerd** [comment]
@jasnell / @rvagg / @mhdawson are we satisfied with the way that things have currently been documented? Are you comfortable with changes to flakyness landing without review?

**Comment by jasnell** [comment]
SGTM

**Comment by rvagg** [comment]
sure
