### ISSUE TITLE
Ava is triggering early bail out in npm 3.x

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#510]
https://github.com/nodejs/citgm/pull/509

>As of ava 0.23.0 it is consistently failing in citgm on most enviroments
>
>In ava 0.23.0 they have introduced a new dependency that limits the
number of cores used in CI. I believe that this is triggering a race
condition bug in npm 3.x and causing the suite to bail early.
>
>Ava 0.22.0 is consistently passing with v6.x and v8.x is consistently passing
with npm 5.x
>
>As such I think it makes sense to simply mark ava as flaky on versions of node
shipping with older versions of npm

**Comment by MylesBorins** [comment]
@novemberborn

Here is a run of 6.x with ava so you can see the failures https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/204/

**Comment by novemberborn** [comment]
@MylesBorins what's weird is that if you look at https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker-nobuild/204/MACHINE=fedora-last-latest-x64/testReport/(root)/citgm/ava_v0_24_0/ it doesn't look like it ran all test files, but there is no error output either.

Since we commit the `package-lock.json` perhaps there is a transitive dependency that's been updated and is now causing these issues, which is not a problem with Node.js 8 (at the moment) since it's got npm 5 which means the offending dependency isn't being installed.

I'm at a loss on how to debug this though, given that the tests just seem to end. That makes me want to blame `tap` but that just seems unlikely. When did these issues start though? The latest `tap` release in our version range came out November 7th.

**Comment by MylesBorins** [comment]
I'm not sure exactly when it happened. But I do know 0.22 is unaffected
